# Generated by Django 2.1.3 on 2019-03-07 21:05

from django.db import migrations, models
import django.db.models.deletion
import personal.models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20190301_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='acceptance_criteria',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_description',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Courses'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='testing_criteria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='courses',
            name='instructor_username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invite',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Courses'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='expires_on',
            field=models.DateField(default=personal.models.one_month_from_today),
        ),
        migrations.AlterField(
            model_name='invite',
            name='level_of_invite',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invite',
            name='sender_username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_user',
            field=models.CharField(max_length=20),
        ),
    ]
