# DEVELOPMENT COMPOSE FILE
# Docker Compose file for launching Django connected to a MySQL server
# running in a separate container. The Docker images are described in
# the docker/ folder below here and the database data is stored in
# db/, the Django application stored starting here.
#
# To run on lab machines, pass other compose file as an argument, e.g.
#   $ docker-compose -f docker-compose.lab.yml up
version: "2.1"

networks:
  # Construct a private network for the Django server and
  # database server to communicate on
  infrastructure:
    external: false

services:
  django:
    restart: always
    build: ./docker/django/
    image: django:dev
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - 8080:8000
    container_name: "django_dev"
    networks:
      # Join the infrastructure network
      - infrastructure
    depends_on:
      - db
 
  db:
    build: ./docker/mysql/
    image: mysql:dev
    volumes:
      - ${PWD}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=django
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
      - MYSQL_DATABASE=djangodocker_db
    container_name: "mysql_dev"
    networks:
      # Join the infrastructure network
      - infrastructure
