# PRODUCTION COMPOSE FILE
# Extracts database values into .env file for production.
#
# DJANGO PORT must always be specified. Configure (with SETUP.txt) or pass in
# through shell.
# NOTE: Dependent on .env file (not available in git repository).
#
# To build an image in production mode:
#   $ docker-compose -f prod.yml build
# (To use in lab, append `-f lab.yml` as well before the build command.)
version: "2.1"

services:
  django:
    restart: always
    image: django:prod
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - SECRET_KEY
      - DEBUG
    container_name: "django"

  db:
    image: mysql:prod
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    container_name: "mysql"
