# Generated by Django 2.1.7 on 2019-03-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assignment_description', models.CharField(blank=True, max_length=200, null=True)),
                ('optional_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('acceptance_criteria', models.CharField(blank=True, max_length=200, null=True)),
                ('testing_criteria', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(blank=True, max_length=30, null=True)),
                ('instructor_username', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('invite_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sender_username', models.CharField(blank=True, max_length=20, null=True)),
                ('rec_username', models.CharField(blank=True, max_length=20, null=True)),
                ('level_of_invite', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateField()),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('submitted_user', models.CharField(blank=True, max_length=20, null=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('submission_number', models.IntegerField()),
                ('submitted_filename', models.CharField(blank=True, max_length=20, null=True)),
                ('assignment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Courses'),
        ),
    ]
