# Generated by Django 2.1.7 on 2019-03-21 20:34

from django.db import migrations, models
import django.db.models.deletion
import personal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assignment_description', models.CharField(max_length=200)),
                ('optional_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('acceptance_criteria', models.CharField(max_length=200)),
                ('testing_criteria', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=30)),
                ('instructor_username', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('invite_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sender_username', models.CharField(max_length=20)),
                ('rec_username', models.CharField(max_length=20)),
                ('level_of_invite', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateField(default=personal.models.one_month_from_today)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('submitted_user', models.CharField(max_length=20)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('submission_number', models.IntegerField(default=1)),
                ('submitted_filename', models.CharField(blank=True, max_length=20, null=True)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_username', models.CharField(max_length=20)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Courses'),
        ),
    ]
