# Generated by Django 2.2 on 2019-04-10 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='rec_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='to user'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='sender_username',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Instructor'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='from user'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user_level',
            field=models.CharField(choices=[('g', 'Grader'), ('s', 'Student'), ('i', 'Instructor')], default='s', max_length=1, verbose_name='User level in course'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_user',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='takes',
            name='user_level',
            field=models.CharField(choices=[('g', 'Grader'), ('s', 'Student'), ('i', 'Instructor')], default='s', max_length=1, verbose_name='User level in course'),
        ),
        migrations.AlterField(
            model_name='takes',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('rec_username', 'course_id', 'user_level')},
        ),
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together={('username', 'course_id', 'user_level')},
        ),
    ]
