# Generated by Django 2.1.7 on 2019-03-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20190301_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='expires_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_number',
            field=models.IntegerField(null=True),
        ),
    ]
