# Generated by Django 2.1.3 on 2019-03-07 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20190307_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('takes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_username', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invite',
            name='rec_username',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='takes',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Courses'),
        ),
    ]
